### ISSUE TITLE
Repository should be called MVP instead of MVP-discuss

### ISSUE THREAD

**Issue by jmichelz** [OPSN/MVP-discuss#8]
I'd like to just use one repository to discuss and to work.  I don't think the discussion by itself is super useful unless it will be translated into action.

**Comment by oresmus** [comment]
I agree action is needed, but (1) ideally the action will involve _more than one_ coding project (and thus more than one repo), (2) I don't see any problem with having a coding project in its own repo, (3) the discussion in this repo is inherently more general than any one coding project, since it includes the question of whether there should be some additional or different coding project.

Of course, once some specific coding project is happening (in its own repo), any discussion specifically about _it_ would belong in that repo, not in this more general one.
